version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.Dev
    volumes:
      - .:/go/src/app
    environment:
      MONGO_HOST: mongo
      REDIS_HOST: redis
      REDIS_CHANNEL: default
      USERNAME: admin
      PASSWORD: admin
#      SLACK_WEBHOOK: "https://hooks.slack.com/services/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"
    depends_on:
      - redis
      - mongo
  redis:
    image: redis:4.0.9-alpine
  mongo:
    image: mongo
