version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.Dev
    volumes:
      - .:/go/src/app
    environment:
      MONGO_HOST: mongo
      REDIS_HOST: redis
      REDIS_CHANNEL: default
      USER: test123
      USER_PASSWORD: test123
    depends_on:
      - redis
      - mongo
  redis:
    image: redis:4.0.9-alpine
  mongo:
    image: mongo
