---
# Storage Class (GCE)
#kind: StorageClass
#apiVersion: storage.k8s.io/v1beta1
#metadata:
# name: fast
#provisioner: kubernetes.io/gce-pd
#parameters:
# type: pd-ssd
---
# Storage Class (AKS)
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fast
  namespace: staging
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
parameters:
  skuName: Standard_LRS
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: staging
  labels:
    name: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongo
---
# Stateful Set
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo
  namespace: staging
spec:
  serviceName: "mongo"
  replicas: 1
  template:
    metadata:
      labels:
        role: mongo
        environment: staging
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo
          command:
            - mongod
            - "--replSet"
            - rs0
            - "--smallfiles"
            - "--noprealloc"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
        - name: mongo-sidecar
          image: cvallance/mongo-k8s-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "role=mongo,environment=staging"
  volumeClaimTemplates:
    - metadata:
        name: mongo-persistent-storage
        annotations:
          volume.beta.kubernetes.io/storage-class: "fast"
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 100Gi
---