---
# Storage Class (GCE)
#kind: StorageClass
#apiVersion: storage.k8s.io/v1beta1
#metadata:
# name: fast
#provisioner: kubernetes.io/gce-pd
#parameters:
# type: pd-ssd
---
# Storage Class (AKS)
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: fast
  namespace: staging
provisioner: kubernetes.io/azure-file
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=1000
  - gid=1000
parameters:
  skuName: Standard_LRS
  storageAccount: mongo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azurefile
  namespace: staging
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: fast
  resources:
    requests:
      storage: 5Gi
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: staging
  labels:
    name: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongo
---
# Stateful Set
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongo
  namespace: staging
spec:
  serviceName: "mongo"
  replicas: 1
  template:
    metadata:
      labels:
        role: mongo
        environment: test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: mongo:3.4
          command:
            - "mongod"
            - "--dbpath=/data/mongo"
            - "--replSet"
            - "rs0"
            - "--bind_ip"
            - "0.0.0.0"
            - "--smallfiles"
            - "--noprealloc"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: persistdisk
              mountPath: /data/mongo
      volumes:
        - name: persistdisk
          persistentVolumeClaim:
            claimName: azurefile
---